# Setup
# title:       <img src="assets/logo3.png" alt="Logo" width="50" height="50">  Edge-Device Large Language Model Competition
title:       Edge-Device Large Language Model Competition
description: NeurIPS 2024 Challenge
# baseurl:     "/edge-llm-challenge.github.io"
paginate:     1
locale:       "en"

# About/contact
author:
  #name:       Author name
#  url:       "https://edge-llms-challenge.github.io" 

#Others
navigation:
  Home: "index"
  Challenge: "challenge"
  Rules: "rules"
  Timeline: "dates"
  Workshop: "schedule"
  Prizes: "prizes"
  Starting Kit: "starter_kit"
  Registration: "registration"
  Feedback: "feedback"
  Leaderboard: "leaderboard"
  Organizers: "organizers"
  #Advisors: "advisors"
  Sponsors: "sponsors"
  Q&A: "question"
# markdown: kramdown
